version: "3.9"
services:
  api01:
    build: .
    environment:
      - QUARKUS_PROFILE=prod
      - REDIS_HOST=redis
    depends_on:
      redis:
        condition: service_healthy
    expose:
      - "8080"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "45MB"

  api02:
    build: .
    environment:
      - QUARKUS_PROFILE=prod
      - REDIS_HOST=redis
    expose:
      - "8080"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "45MB"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "12MB"

  redis:
    image: redis:7.2-alpine
    command: redis-server --save "" --appendonly no --maxmemory 190mb --maxclients 10000
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 4s
      timeout: 2s
      retries: 3
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "235MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
