version: "3.9"

services:
  api01: &api-base
    build: .
    container_name: api01
    hostname: api01
    environment:
      - QUARKUS_PROFILE=prod
      - QUARKUS_OPTS=-Xms100m -Xmx100m -XX:+UseShenandoahGC
    expose:
      - "8080"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  api02:
    <<: *api-base
    container_name: api02
    hostname: api02

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "60MB"

  redis:
    image: redis:7.2-alpine
    container_name: redis
    command: redis-server --maxclients 20000 --maxmemory 60mb --maxmemory-policy allkeys-lru --save "" --appendonly no --io-threads 4 --io-threads-do-reads yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 4s
      timeout: 2s
      retries: 3
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "90MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true