version: "3.9"
services:
  api01:
    container_name: api01
    build: .
    environment:
      - QUARKUS_PROFILE=prod
    depends_on:
      redis:
        condition: service_healthy
    expose:
      - "8080"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "100MB"

  api02:
    build: .
    container_name: api02
    environment:
      - QUARKUS_PROFILE=prod
    expose:
      - "8080"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "100MB"

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    networks:
      - backend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "75MB"

  redis:
    image: redis:7.2-alpine
    container_name: redis
    command: redis-server --maxclients 10000 --maxmemory-policy allkeys-lru --save "" --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 4s
      timeout: 2s
      retries: 3
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "75MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
