version: "3.9"
services:
  api01:
    container_name: api01
    build: .
    environment:
      - QUARKUS_PROFILE=prod
    depends_on:
      redis:
        condition: service_healthy
    expose:
      - "8080"
    networks:
      - backend
      - payment-processor


  api02:
    build: .
    container_name: api02
    environment:
      - QUARKUS_PROFILE=prod
    expose:
      - "8080"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor


  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    networks:
      - backend
    restart: unless-stopped


  redis:
    image: redis:7.2-alpine
    container_name: redis
    command: redis-server --maxclients 20000 --maxmemory-policy allkeys-lru --save "" --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 4s
      timeout: 2s
      retries: 3
    networks:
      - backend


  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
      POSTGRES_USER: rinha
    volumes:
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    command: postgres -c max_connections=300 -c shared_buffers=28MB -c work_mem=512kB -c maintenance_work_mem=2MB -c fsync=off -c full_page_writes=off -c synchronous_commit=off
    networks:
      - backend
      - payment-processor


networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
